language: python

cache: pip

matrix:
  include:
    python: 2.7
    python: 3.5
    python: 3.6
    python: 3.7
    python: pypy
    python: pypy3
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=2.7.10
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.5.0
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=pypy-2.6.0
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

before_install:
  - bash .ci/deps.${TRAVIS_OS_NAME}.sh

install:
  - pip install --upgrade pip
  - pip install nose coveralls testfixtures
  - pip install --editable .

before_script:
  - bash .ci/pre.${TRAVIS_OS_NAME}.sh

script:
  - nosetests --with-coverage --cover-package=prettyconf

after_success:
  - coveralls
